### ISSUE TITLE
Sharing Trained Models

### ISSUE THREAD

**Issue by cancam** [PerdonLiu/CSE-Autoloss#1]
Hi colleagues,

First of all, thank you for sharing this work. I am wondering if it is possible to share the 12 epoch trained model with ResNet-50 backbone?

Thank you!
Baris.

**Comment by PerdonLiu** [comment]
Hi, thanks for your attention to our work. The trained models with ResNet-50 for Faster R-CNN(https://drive.google.com/file/d/1WtKEJo5bKp4rKq6382CXs7dsd90sSWv1/view) and FCOS(https://drive.google.com/file/d/1c53qgqsIUnQ1EuOksGGfy7gdlh7PWR2S/view) are released. Please see more details in README.
