### ISSUE TITLE
searching code?

### ISSUE THREAD

**Issue by lulongfei-luffy** [PerdonLiu/CSE-Autoloss#2]
I want to follow your code for my own task, but I did not find the code for searching loss. Could you public loss searching code?
Thank you very much.

**Comment by PerdonLiu** [comment]
Hi, thank you for your attention to our work. This work is done when the first author was an intern in Huawei. Unfortunately, I am sorry that we don't plan to release the search code according to the information security requirements in Huawei.

**Comment by lulongfei-luffy** [comment]
What a pity, but thank you very much for your reply.
