### ISSUE TITLE
Some details?

### ISSUE THREAD

**Issue by GuHY777** [PerdonLiu/CSE-Autoloss#3]
Hi! I like your work very much, and I want to follow it. But from the paper, some details are not described very clearly. I hope you can help me understand the question：

**The loss function can be represented as a directed acyclic graph(DAG), but how can I design the cross-over and mutation for the DAG. Some details of the cross-over and mutation are not found in the paper.**

**Comment by PerdonLiu** [comment]
Hi, GuHong, thanks for your interest. Our evolution implementation including cross-over and mutation is based on [DEAP](https://deap.readthedocs.io/), which is a perfect genetic programming framework for this task. You may refer to [this specific page](https://deap.readthedocs.io/en/master/tutorials/advanced/gp.html)  for your question. 

Please feel free to contact me if you have any further questions.

**Comment by GuHY777** [comment]
That's great!

I also have a specific implementation detail, that is, how are the properties of monotonicity and convergence achieved? The method I can think of is to use interpolation to determine whether to obey monotonicity.

**Comment by PerdonLiu** [comment]
Our implementation is to generate some data points and see if the loss values satisfy these properties.
